"""Project data of the roman_fourier unit tests, bound to the shared harness.

The test machinery is the same in every Cocoa project and lives once in
external_modules/code/cosmolike_core/cocoa_testing.py: frozen-state
verification, the chi2 pipeline, worker-subprocess isolation (each test
quantity is computed in a fresh Python process), the race and baryon
checks, the CFASTPT-vs-FASTPT and Halofit-vs-EE2 comparisons, and the
terminal reports. This module is the project's "shim": it holds what
belongs to roman_fourier alone (the examples table of the Fourier-space
cosmic-shear, 3x2pt and 2x2pt configurations, the TATT point, the
accuracy knobs, the dataset names and the CFASTPT-vs-FASTPT comparison
settings), builds one cocoa_testing.CocoaTestHarness from them, and
re-exports the harness functions as module-level names.

Re-exporting means an assignment such as `verify_frozen = _H.verify_frozen`:
a test module that runs `import cocoa_test_utils as u` can then call
u.verify_frozen(). _H.verify_frozen is a bound method, a function that
remembers the instance _H, so the call needs no harness argument. The
test modules in data_vector/, conftest.py, generate_frozen_reference.py,
generate_photoz_convention_figure.py and the worker subprocesses import
only this module.

Everything a test evaluates lives under tests/frozen/, pinned byte for
byte by the SHA-256 hashes of tests/manifest_sha256.json and verified
before any model is built. Refreshing it is a deliberate maintainer
action (generate_frozen_reference.py --overwrite).
"""

import os
import sys

# ---- tests/ paths -----------------------------------------------------------

# Everything the tests read or write lives relative to this folder, so
# the suite works no matter which directory pytest is launched from
# (__file__ is this module's own path; dirname strips the file name).
TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
FROZEN_DIR = os.path.join(TESTS_DIR, "frozen")
MANIFEST_FILE = os.path.join(TESTS_DIR, "manifest_sha256.json")
REFERENCE_FILE = os.path.join(FROZEN_DIR, "reference_chi2.json")

# ---- the shared machinery ---------------------------------------------------

# The import is path-based (tests/ is three folders below Cocoa/, which
# holds external_modules/code/cosmolike_core), so it works before
# start_cocoa.sh sets up the Python path; the check avoids inserting the
# folder twice when the module is imported again in the same process.
_CORE_DIR = os.path.abspath(os.path.join(
    TESTS_DIR, "..", "..", "..", "external_modules", "code",
    "cosmolike_core"))
if _CORE_DIR not in sys.path:
    sys.path.insert(0, _CORE_DIR)
import cocoa_testing as _cct

# ---- the project data ------------------------------------------------------

# ---- TATT -------------------------------------------------------------------

# The TATT (Tidal Alignment and Tidal Torquing, an intrinsic-alignment
# model with tidal second-order terms) tests replace these values in the
# frozen point: roman_A2_1 is the amplitude of the tidal-torquing term,
# roman_A2_2 its redshift exponent, and roman_BTA_1 the density-weighting
# coefficient b_TA. In the NLA reference point A2_1 and BTA_1 are zero, so
# the nonzero values here make the TATT reference exercise the
# second-order terms.
TATT_POINT = {
    "roman_A2_1": 0.05,
    "roman_BTA_1": 0.05,
    "roman_A2_2": -1.51541,
}

# The TATT variants evaluate against a data vector generated with TATT at
# the fiducial point. Against an NLA-based vector the TATT chi2 would sit
# away from its minimum, where it responds linearly (not quadratically)
# to tiny numerical changes, and harmless rounding-level shifts would eat
# much of the 0.2 chi2 band of the reference tests. Both examples share
# one data set, so one full-length vector generated by the example2 TATT
# model (3x2pt) serves every configuration: cosmolike masks the entries
# of the probes a likelihood does not use. Maps descriptor -> generator.
TATT_GENERATORS = {
    "tatt_roman_fourier.dataset": "example2",
}

# ---- configurations ---------------------------------------------------------

# The three frozen configurations, by name. Keys of each entry:
#   frozen_module  = the generated configuration module under frozen/;
#   provenance     = the example yaml it was frozen from (a human-readable
#                    snapshot under frozen/, never loaded by a test);
#   likelihood     = the Cobaya component name, needed to reach that block
#                    inside the loaded configuration dictionary;
#   tatt_dataset   = the TATT-generated dataset of the TATT variants;
#   source_likelihood = for example2_2x2pt, the block of the example yaml
#                    that is renamed to combo_2x2pt at freeze time.
EXAMPLES = {
    "example1": {
        "frozen_module": "frozen_config_example1.py",
        "provenance": "EXAMPLE_EVALUATE1.yaml",
        "likelihood": "roman_fourier.cosmic_shear",
        "tatt_dataset": "tatt_roman_fourier.dataset",
    },
    "example2": {
        "frozen_module": "frozen_config_example2.py",
        "provenance": "EXAMPLE_EVALUATE2.yaml",
        "likelihood": "roman_fourier.combo_3x2pt",
        "tatt_dataset": "tatt_roman_fourier.dataset",
    },
    "example2_2x2pt": {
        "frozen_module": "frozen_config_example2_2x2pt.py",
        "provenance": "EXAMPLE_EVALUATE2.yaml",
        "source_likelihood": "roman_fourier.combo_3x2pt",
        "likelihood": "roman_fourier.combo_2x2pt",
        "tatt_dataset": "tatt_roman_fourier.dataset",
    },
}

# ---- accuracy knobs ---------------------------------------------------------

# High-accuracy settings for the accuracy advisory checks
# (test_accuracy.py). This is a Fourier-space project: there is no
# lmax likelihood option (the ell range lives in the dataset), so
# unlike the real-space projects the block carries no lmax key.
HIGH_ACCURACY_LIKELIHOOD = {
    # boost 3 is the highest value at which every scanned project still
    # evaluates correctly (desy1xplanck breaks down above it), so the
    # all-knobs check compares the default against 3; the one-at-a-time
    # scan keeps 5 as a deliberate stress test
    "accuracyboost": 3.0,       # default 2.0
    "internal_accuracyboost": 2.0, # default 1.0 (denser convolution grid)
    "integration_accuracy": 10,  # default 0
    "kmax_boltzmann": 40.0,     # default 7.5
}

# The one-at-a-time scan of test_accuracy.py: each entry is (label,
# likelihood overrides, camb extra_args overrides), evaluated alone on
# the example2 NLA configuration before the all-knobs checks, so a
# large all-knobs delta can be attributed to the knob causing it. The
# accuracyboost=5 entry is a stress test, beyond what measuring the
# default numerics needs: an interface breakdown shows up there as an
# explosive delta (in desy1xplanck it exposed one, a suspected fixed-size
# table). Investigation order when several knobs move the chi2: raise the
# cosmolike accuracyboost first (cheap), then camb k_per_logint, and
# only then camb AccuracyBoost (expensive at run time): an apparent
# CAMB sensitivity can masquerade as unresolved cosmolike-side
# resolution, so the cheap knobs must be settled before the expensive
# one is blamed. kmax_boltzmann and camb kmax are one physical cutoff
# seen from the two sides, so the scan moves them together.
ACCURACY_KNOBS = [
    ("accuracyboost -> 3", {"accuracyboost": 3.0}, {}),
    ("accuracyboost -> 5 (stress)", {"accuracyboost": 5.0}, {}),
    ("internal_accuracyboost 1->2", {"internal_accuracyboost": 2.0}, {}),
    ("integration_accuracy -> 10", {"integration_accuracy": 10}, {}),
    ("kmax_boltzmann -> 40 + camb kmax -> 50",
     {"kmax_boltzmann": 40.0}, {"kmax": 50.0}),
    ("camb AccuracyBoost -> 2", {}, {"AccuracyBoost": 2.0}),
    ("camb k_per_logint -> 50", {}, {"k_per_logint": 50}),
]

# Pass limit of the CFASTPT-vs-FASTPT comparison at FASTPT_LOW_SETTINGS.
# At each point both implementations print their theory data vector, and
# the tested number is delta^T C^-1 delta, with delta the difference of
# the two vectors and C^-1 the masked inverse covariance: the chi2 of the
# implementation difference, zero when the vectors agree. 0.2 is the chi2
# band of the other reference checks (CHI2_TOLERANCE). With the two-grid
# fastpt theory block this project falls inside it at accuracyboost: 2,
# the doubled output-table density (max delta chi2 = 0.112 over the 30
# points), while a single shared grid of 1,100 points reaches 87184
# across the prior.
FASTPT_COMPARISON_TOLERANCE = 0.2

# The python FAST-PT side has numerical settings of its own, read by
# the fastpt theory block from its extra_args block
# (external_modules/code/PyFAST-PT/fastpt.py, symlinked into cobaya
# as theories/fastpt). The block computes on two grids: accuracyboost
# multiplies the density of the output table cosmolike reads with
# linear interpolation (the accuracy driver), and
# internal_accuracyboost the density of the internal grid the FFTLog
# convolutions run on; a cubic spline in log k upsamples the terms
# from one grid onto the other. Both boosts default to 1.0 = the
# converged configuration; low here carries accuracyboost: 2, the
# doubled output density this project's precision needs (the value
# its example yamls recommend), hard-coded so the test keeps
# evaluating this exact configuration even if the yamls change.
# High doubles both boosts again, so the advisory column shows the
# residual grid response of low. kmax_boltzmann and extrap_kmax (both
# in 1/Mpc) keep the block's defaults: CAMB computes the P_lin the block
# reads up to 7.5/Mpc, and its interpolator extrapolates to 250/Mpc.
FASTPT_LOW_SETTINGS = {
    "accuracyboost": 2.0,
    "internal_accuracyboost": 1.0,
    "kmax_boltzmann": 7.5,
    "extrap_kmax": 250.0,
}

FASTPT_HIGH_SETTINGS = {
    "accuracyboost": 4.0,
    "internal_accuracyboost": 2.0,
    "kmax_boltzmann": 7.5,
    "extrap_kmax": 250.0,
}

# ---- project-independent constants ------------------------------------------

# These are identical in every project and live in the core module.
REQUIRED_OMP_THREADS = _cct.REQUIRED_OMP_THREADS
CHI2_TOLERANCE = _cct.CHI2_TOLERANCE
RACE_TOLERANCE = _cct.RACE_TOLERANCE
RACE_PERTURBATIONS = _cct.RACE_PERTURBATIONS
HIGH_ACCURACY_CAMB_EXTRA_ARGS = _cct.HIGH_ACCURACY_CAMB_EXTRA_ARGS
BARYON_METHODS = _cct.BARYON_METHODS
BARYON_POINT_OVERRIDES = _cct.BARYON_POINT_OVERRIDES

# The 30 CFASTPT-vs-FASTPT comparison points under this project's
# sampled-parameter prefix; the values are identical in every project.
FASTPT_COMPARISON_POINTS = _cct.fastpt_comparison_points("roman")

# The ten Halofit-vs-EE2 comparison cosmologies (checks NL1-NL2); the
# parameters are cosmology-level (omegam/ns/As, no project prefix), so
# the list is shared verbatim by every project.
NONLINEAR_COMPARISON_POINTS = _cct.NONLINEAR_COMPARISON_POINTS

# ---- the harness -----------------------------------------------------------

# One CocoaTestHarness instance, _H, binds the shared machinery to this
# project's data; the assignments below re-export its functions under the
# names the test modules, conftest.py and the worker subprocesses use.
_H = _cct.CocoaTestHarness(
    worker_file=__file__,
    interface_module="cosmolike_roman_fourier_interface",
    examples=EXAMPLES,
    tatt_point=TATT_POINT,
    accuracy_knobs=ACCURACY_KNOBS,
    high_accuracy_likelihood=HIGH_ACCURACY_LIKELIHOOD,
    fastpt_low_settings=FASTPT_LOW_SETTINGS,
    fastpt_high_settings=FASTPT_HIGH_SETTINGS,
    fastpt_points=FASTPT_COMPARISON_POINTS,
    # the scale-cut masks the CFASTPT-vs-FASTPT sweeps accept (the
    # --mask option of conftest.py): "frozen" keeps the contract mask,
    # "ones" the frozen all-ones mask (every data point kept, no scale
    # cuts) through tatt_roman_fourier_ones.dataset
    fastpt_masks=("frozen", "ones"),
)

# ---- module functions re-exported from the core (no project state) ----------
# Each line binds a name of this module to the core's function object; no
# function runs here.
require_cocoa_environment = _cct.require_cocoa_environment
assert_omp_threads = _cct.assert_omp_threads
sha256_of = _cct.sha256_of
make_model = _cct.make_model
evaluate_chi2 = _cct.evaluate_chi2
_evaluate_cached = _cct._evaluate_cached
_load_datavector = _cct._load_datavector
_baryon_method = _cct._baryon_method
_baryon_dataset = _cct._baryon_dataset
report_chi2_test = _cct.report_chi2_test
report_race_test = _cct.report_race_test
report_accuracy = _cct.report_accuracy
report_knob = _cct.report_knob
report_fastpt_comparison = _cct.report_fastpt_comparison
report_nonlinear_comparison = _cct.report_nonlinear_comparison

# ---- bound methods of the harness (the machinery, project-bound) ------------
# Some names are looked up by their spelling from another process or file,
# so a rename breaks the tests only when that path runs (AttributeError):
# _worker (called inside every worker subprocess), _fastpt_comparison_block
# and _nonlinear_comparison_block (called by the child programs of the
# comparison sweeps), and _cct and _H (read by conftest.py).
compute_manifest = _H.compute_manifest
verify_frozen = _H.verify_frozen
load_reference = _H.load_reference
_frozen_module = _H._frozen_module
load_frozen_info = _H.load_frozen_info
load_frozen_point = _H.load_frozen_point
build_point = _H.build_point
_single_model_chi2_impl = _H._single_model_chi2_impl
_ten_in_a_row_impl = _H._ten_in_a_row_impl
_baryon_accuracy_delta_impl = _H._baryon_accuracy_delta_impl
_baryon_drift_chi2_impl = _H._baryon_drift_chi2_impl
single_model_chi2 = _H.single_model_chi2
ten_in_a_row_chi2 = _H.ten_in_a_row_chi2
baryon_accuracy_delta = _H.baryon_accuracy_delta
baryon_drift_chi2 = _H.baryon_drift_chi2
_worker = _H._worker
_run_isolated = _H._run_isolated
_fastpt_comparison_info = _H._fastpt_comparison_info
_fastpt_comparison_block = _H._fastpt_comparison_block
_run_fastpt_comparison_worker = _H._run_fastpt_comparison_worker
cfastpt_vs_fastpt_chi2s = _H.cfastpt_vs_fastpt_chi2s
# the child program of the Halofit-vs-EE2 sweep calls
# u._nonlinear_comparison_block by name, so this re-export is required
_nonlinear_comparison_block = _H._nonlinear_comparison_block
halofit_vs_ee2_dchi2s = _H.halofit_vs_ee2_dchi2s
